---
- hosts: "backendservers"
  user: ansible
  become: yes
  become_method: sudo
  become_user: root
  tasks:
  - name: install apache
    yum: name=httpd state=latest
  - name: start httpd
    service: name=httpd state=started  
